features:
  account: true
  client: true

---

spring:
  profiles.active: qa
  jpa.properties.hibernate.generate_statistics: true
  integration.legacyAccountingSystem:
    baseUrl: "http://localhost:8888/api"
    accountsEndpoint: "/account"
  datasource.hikari.pool-name: hikari-connection-pool
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
  liquibase: #https://javadeveloperzone.com/spring-boot/spring-boot-liquibase-example/
    enabled: true
    contexts: prod, qa
    liquibase-schema: liquibase
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: classpath:/db-changelog.xml
    rollback-file: liquibase-rollback.sql
    test-rollback-on-update: true

server:
  port: 8080
  servlet.context-path: /dbo
  tomcat:
    mbeanregistry.enabled: true
    threads.max: 100

management:
  metrics:
    enable.all: true
    export.prometheus.enabled: true
    web.server.request.autotime.enabled: true
  endpoints.web.exposure.include: '*'
  endpoint:
    health.show-details: always
    shutdown.enabled: true
    prometheus.enabled: true

httpPool:
  maxTotal: 100
  defaultMaxPerRoute: 10
  connectTimeout: 5000
  connectionRequestTimeout: 1000
  socketTimeout: 65000
  validateAfterInactivity: 2000

---

spring:
  config.activate.on-profile: test
  main.lazy-initialization: true
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

---

spring:
  config.activate.on-profile: it
  main.lazy-initialization: true
  datasource:
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:memory:dbo-db;create=true
    username: APP
    password: APP
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
  liquibase:
    test-rollback-on-update: false

---

spring:
  config.activate.on-profile: qa
  datasource:
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:dbo-db;create=true
    username: APP
    password: APP
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 600000

---

spring:
  config.activate.on-profile: qa2
  datasource:
    driverClassName: org.apache.derby.jdbc.ClientDriver
    url: jdbc:derby://localhost/dbo-db;create=true
    username: APP
    password: APP
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 600000

---

spring:
  config.activate.on-profile: preprod
  datasource:
    driverClassName: org.postgresql.Driver
    url:  #should be externalized
    username: #should be externalized
    password: #should be externalized
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 18000000

---

spring:
  config.activate.on-profile: prod
  datasource:
    driverClassName: org.postgresql.Driver
    url: #should be externalized
    username: #should be externalized
    password: #should be externalized
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 18000000
  liquibase:
    contexts: prod
